import Foundation
import XCTest

/// Locates and decodes the shared golden vectors at <repo>/tools/golden,
/// generated by tools/gen_golden.js from the original TypeScript logic.
enum Golden {
    static func repoRoot(file: StaticString = #filePath) -> URL {
        // <repo>/ios/EpycCore/Tests/EpycCoreTests/<thisFile>
        var url = URL(fileURLWithPath: "\(file)")
        for _ in 0..<5 { url.deleteLastPathComponent() }
        return url
    }

    static func data(_ name: String) throws -> Data {
        let url = repoRoot().appendingPathComponent("tools/golden/\(name)")
        return try Data(contentsOf: url)
    }

    static func decode<T: Decodable>(_ type: T.Type, from name: String) throws -> T {
        try JSONDecoder().decode(T.self, from: data(name))
    }
}
