include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/firebase_options.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
